// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAi4pjUA9_bdMNBGgygkgeUuaTJyjZ9tco',
    appId: '1:444342639779:web:bf811519b05ac91ccc3316',
    messagingSenderId: '444342639779',
    projectId: 'fitnesstracker-c1c5c',
    authDomain: 'fitnesstracker-c1c5c.firebaseapp.com',
    storageBucket: 'fitnesstracker-c1c5c.firebasestorage.app',
    measurementId: 'G-DQYNJDJE0X',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD9QcWtuuQ6c9RBpV4lcLvf-gfWjCqPaUQ',
    appId: '1:444342639779:android:827732fbba22770bcc3316',
    messagingSenderId: '444342639779',
    projectId: 'fitnesstracker-c1c5c',
    storageBucket: 'fitnesstracker-c1c5c.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAi4pjUA9_bdMNBGgygkgeUuaTJyjZ9tco',
    appId: '1:444342639779:web:b85d43fa5d6f0651cc3316',
    messagingSenderId: '444342639779',
    projectId: 'fitnesstracker-c1c5c',
    authDomain: 'fitnesstracker-c1c5c.firebaseapp.com',
    storageBucket: 'fitnesstracker-c1c5c.firebasestorage.app',
    measurementId: 'G-ERG72SBXS1',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCsALLvr37kjSPxWCX-0b_rzVP7fBmJRMw',
    appId: '1:444342639779:ios:b8878b86f9d2ca6ccc3316',
    messagingSenderId: '444342639779',
    projectId: 'fitnesstracker-c1c5c',
    storageBucket: 'fitnesstracker-c1c5c.firebasestorage.app',
    iosBundleId: 'com.example.fitnessApp',
  );

}